<?php
return array(
    'PHONE'                 => '',
    'APP_KEY'               => '123456',
    'URL_MODEL'             =>  3,
    'SESSION_AUTO_START'    =>  false,
    'DEFAULT_AJAX_RETURN'   =>  'JSON',
    'LOAD_EXT_CONFIG'       =>  'code',
    'SMS_SINATURE'          =>  '',
    'SMS_OVER_TIME'         =>  1800,
    'SHARE'                 => '',   //分享跳转地址
    'register'              => '',   //推荐注册地址
    //支付宝信息
    'gatewayUrl'            =>  'https://openapi.alipay.com/gateway.do',
    'appId'                 =>  '',
    //商户私钥
    'rsaPrivateKey'         =>  '',
    //支付宝公钥
    'alipayrsaPublicKey'            => '',
     'areaColor'            => array(
                            "北京市" => "#FFB6C1",
                            "天津市" => "#DC143C",
                            "河北省" => "#DB7093",
                            "山西省" => "#FF1493",
                            "内蒙古自治区" => "#C71585",
                            "辽宁省" => "#D8BFD8",
                            "吉林省" => "#EE82EE",
                            "黑龙江省" => "#FF00FF",
                            "上海市" => "#800080",
                            "江苏省" => "#4B0082",
                            "浙江省" => "#9370DB",
                            "安徽省" => "#483D8B",
                            "福建省" => "#0000FF",
                            "江西省" => "#191970",
                            "山东省" => "#6495ED",
                            "河南省" => "#778899",
                            "湖北省" => "#1E90FF",
                            "湖南省" => "#87CEEB",
                            "广东省" => "#00BFFF",
                            "广西壮族自治区" => "#00FFFF",
                            "海南省" => "#00FF7F",
                            "重庆市" => "#2E8B57",
                            "四川省" => "#006400",
                            "贵州省" => "#ADFF2F",
                            "云南省" => "#FFFF00",
                            "西藏自治区" => "#FF4500",
                            "陕西省" => "#A52A2A",
                            "甘肃省" => "#DEB887",
                            "青海省" => "#F4A460",
                            "宁夏回族自治区" => "#FF6347",
                            "新疆维吾尔自治区" => "#8B0000",
                            "台湾" => "#CD5C5C",
                            "香港" => "#4169E1",
                            "澳门" => "#4682B4",
                            )
    );